### ISSUE TITLE
Windows IE support

### ISSUE THREAD

**Issue by PavMel** [antoinevastel/picasso-like-canvas-fingerprinting#1]
Hi, Antoine. Thank you for your very interesting  project. Is there any way to get it work in IE? I asked you because I'm absolutely not a javascript programmer.

**Comment by antoinevastel** [comment]
Hi, it seems like the canvas APIs used In this project are available starting from IE 9. So, it should be possible to make it work for IE >= 9 if we get rid of the ES6 syntax. However, I'm not sure I'll have time for this soon. You can try to use a transpolar like Babel otherwise.

**Comment by PavMel** [comment]
I'v used Babel with no luck, but in any case thank you for explanation.
